name: Build and deploy .NET Core app to Azure Container App app-bancodeitens-api

on:
  push:
    branches:
      - main # Monitorar o branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Jose-Marcello/bancodeitens_backend
          ref: main 

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          # Usa o login do Administrador do ACR
          login-server: acrbancoitensdev.azurecr.io
          username: ${{ secrets.ACR_USERNAME }} # acrbancoitensdev
          password: ${{ secrets.ACR_PASSWORD }} # Senha que você tem no Secret

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          # Configurações do App (aponta para a subpasta correta)
          appSourcePath: 'BancoDeItensWebApi'
          dockerfilePath: BancoDeItensWebApi/Dockerfile 
          
          # Credenciais de Destino (Não precisa de SP, usa o contexto do ACR)
          containerAppName: app-bancodeitens-api
          resourceGroup: rg-banco-itens-dev
          acrName: acrbancoitensdev
          imageToBuild: acrbancoitensdev.azurecr.io/app-bancodeitens-api:${{ github.sha }}
          targetPort: 8080
          ingress: external
