name: Trigger auto deployment for app-bancodeitens-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-bancodeitens-api-AutoDeployTrigger-9d77b34b-3c04-40a9-8ea9-336711171b0a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APPBANCODEITENSAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPBANCODEITENSAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPBANCODEITENSAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}BancoDeItensWebApi
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrbancoitensdev.azurecr.io
          registryUsername: ${{ secrets.APPBANCODEITENSAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPBANCODEITENSAPI_REGISTRY_PASSWORD }}
          containerAppName: app-bancodeitens-api
          resourceGroup: rg-banco-itens-dev
          imageToBuild: acrbancoitensdev.azurecr.io/app-bancodeitens-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


